version: "3"
services:
  strapiDB:
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: strapi
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      # - ./data:/var/lib/postgresql/data/ # if you want to use a bind folder

    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    logging:
      driver: none
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  strapi-data:

