name: Cypress

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: ./publish-frontend
        steps:
        - uses: actions/checkout@v2
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            start: npm run develop
            wait-on: 'http://localhost:3000'
