name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chromium, firefox, webkit]
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: strapi
          POSTGRES_PASSWORD: password
          POSTGRES_DB: strapi
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Seed database
        run: npm run seed
      - name: Build apps
        run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project=${{ matrix.browsers }}
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        if: always()
        with:
          name: traces
          path: test-results/
          retention-days: 30
