name: Playwright Tests
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browsers: [chromium, firefox, webkit]
    services:
      postgres:
        image: postgres:14
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: strapi
          POSTGRES_PASSWORD: password
          POSTGRES_DB: strapi
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
    - name: Install dependencies
      run: npm ci
    - name: Seed database
      run: npm run seed
    - name: Build apps
      run: npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ matrix.browsers }}
    - name: Run Playwright tests
      run: npx playwright test --project=${{ matrix.browsers }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
